    \
    sed -e ' \
        s/APP_DEBUG=.*/APP_DEBUG=false/; \
        s/LOG_CHANNEL=.*/LOG_CHANNEL=errorlog/; \
        s/DB_CONNECTION=.*/DB_CONNECTION=sqlite/; \
        s%DB_DATABASE=.*%DB_DATABASE=database/database.sqlite%; \
        ' \
        /var/www/html/.env.example > /var/www/html/.env; \
    \
    chown -R www-data:www-data /var/www/html;