name: Build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        variant: [apache, fpm, fpm-alpine]
        arch: [amd64, i386]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '1'
        submodules: true

    - name: Fix image
      if: matrix.arch == 'i386'
      run: |
        sed -i -e 's/FROM php/FROM i386\/php/g' "0/${{ matrix.variant }}/Dockerfile"

    - name: Update base image
      if: matrix.arch == 'i386'
      run: |
        docker pull i386/php:7.4-${{ matrix.variant }}

    - name: Update base image
      if: matrix.arch != 'i386'
      run: |
        docker pull php:7.4-${{ matrix.variant }}

    - name: Build image ${{ matrix.variant }} ${{ matrix.arch }}
      run: |
        docker build 0/${{ matrix.variant }} -t officelife:${{ matrix.variant }}
        docker images

    - name: Test image ${{ matrix.variant }} ${{ matrix.arch }}
      run: |
        test/run.sh officelife:${{ matrix.variant }}

    - name: Get version
      id: version
      if: github.ref == 'refs/heads/main' && matrix.arch != 'i386'
      run: |
        version=$(cat 0/version)
        echo "::set-output name=version::$version"

    - name: Publish package
      if: github.ref == 'refs/heads/main' && matrix.arch != 'i386'
      run: |
        echo "$password" | docker login ghcr.io -u $username --password-stdin
        for version in ${{ matrix.variant }} ${{ steps.version.output.version }}-${{ matrix.variant }}; do
          docker tag officelife:${{ matrix.variant }} ghcr.io/officelifehq/officelife-dev:$version
          docker push ghcr.io/officelifehq/officelife-dev:$version
        done
      env:
        username: ${{ secrets.CR_USER }}
        password: ${{ secrets.CR_PAT }}

#  test:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v2
#    - name: Test update script
#      run: |
#        hash_before=$(git write-tree)
#        ./update.sh
#        bash -c "[[ $hash_before = $(git add -A && git write-tree) ]]"
